# Generated by Django 4.2.2 on 2023-06-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicao',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.AddField(
            model_name='posicao',
            name='nome_resumido',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
