# Generated by Django 4.2.2 on 2023-06-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nome_posicao_nome_completo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_resumido', models.CharField(default=None, max_length=3)),
                ('nome_completo', models.CharField(max_length=50)),
            ],
        ),
    ]
