# Generated by Django 4.2.2 on 2023-06-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.posicao')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.time')),
            ],
        ),
    ]
