# Generated by Django 4.2.2 on 2023-06-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jogador_reserva'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jogador',
            new_name='Atleta',
        ),
    ]
